field.formatter.settings.modal_popup_text:
  type: mapping
  label: Text in modal formatter settings
  mapping:
    display_text:
      type: string
      label: 'Display text'
    title:
      type: string
      label: 'Title'
    trigger_element:
      type: string
      label: 'Trigger element'
    options:
      type: sequence
      label: 'Options'
      sequence:
      - type: string
        label: 'Option'
